"""Cria tabelas de eventos e ingressos

Revision ID: 2b8e9e4d5d1a
Revises: 
Create Date: 2026-09-27 16:54:09.460307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b8e9e4d5d1a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('data', sa.DateTime(timezone=True), nullable=False),
    sa.Column('local', sa.String(length=150), nullable=False),
    sa.Column('lote_ingressos_disponiveis', sa.Integer(), nullable=False),
    sa.Column('banner_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_id'), 'eventos', ['id'], unique=False)
    op.create_index(op.f('ix_eventos_nome'), 'eventos', ['nome'], unique=False)
    op.create_table('ingressos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('assento', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('DISPONIVEL', 'RESERVADO', 'VENDIDO', name='statusingresso'), nullable=False),
    sa.Column('dono_email', sa.String(length=150), nullable=True),
    sa.Column('pdf_url', sa.String(length=255), nullable=True),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingressos_id'), 'ingressos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingressos_id'), table_name='ingressos')
    op.drop_table('ingressos')
    op.drop_index(op.f('ix_eventos_nome'), table_name='eventos')
    op.drop_index(op.f('ix_eventos_id'), table_name='eventos')
    op.drop_table('eventos')
    # ### end Alembic commands ###
