"""cria_tabelas_usuarios_eventos_e_ingressos

Revision ID: 466a96710f84
Revises: 
Create Date: 2026-10-01 19:32:32.562082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '466a96710f84'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('papel', sa.String(length=20), server_default=sa.text("'user'"), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("papel IN ('user', 'organizer')", name='ck_usuarios_papel'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_usuarios_email', 'usuarios', [sa.literal_column('lower(email)')], unique=True)
    op.create_table('eventos',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('organizador_id', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('local', sa.String(length=150), nullable=False),
    sa.Column('data', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_ingressos', sa.Integer(), nullable=False),
    sa.Column('ingressos_disponiveis', sa.Integer(), nullable=False),
    sa.Column('banner_key', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ingressos_disponiveis >= 0 AND ingressos_disponiveis <= total_ingressos', name='ck_eventos_estoque'),
    sa.CheckConstraint('total_ingressos > 0', name='ck_eventos_total'),
    sa.ForeignKeyConstraint(['organizador_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_eventos_data', 'eventos', ['data'], unique=False, postgresql_where=sa.text('ativo'))
    op.create_index('ix_eventos_organizador', 'eventos', ['organizador_id'], unique=False)
    op.create_table('ingressos',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('evento_id', sa.BigInteger(), nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=10), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('codigo', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('pdf_key', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('pronto_em', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status <> 'READY' OR pdf_key IS NOT NULL", name='ck_ingressos_pdf'),
    sa.CheckConstraint("status IN ('PENDING', 'READY', 'FAILED')", name='ck_ingressos_status'),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo', name='uq_ingressos_codigo'),
    sa.UniqueConstraint('evento_id', 'usuario_id', name='uq_ingressos_evento_usuario')
    )
    op.create_index('ix_ingressos_evento', 'ingressos', ['evento_id'], unique=False)
    op.create_index('ix_ingressos_usuario', 'ingressos', ['usuario_id', sa.literal_column('criado_em DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ingressos_usuario', table_name='ingressos')
    op.drop_index('ix_ingressos_evento', table_name='ingressos')
    op.drop_table('ingressos')
    op.drop_index('ix_eventos_organizador', table_name='eventos')
    op.drop_index('ix_eventos_data', table_name='eventos', postgresql_where=sa.text('ativo'))
    op.drop_table('eventos')
    op.drop_index('uq_usuarios_email', table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
